version: '3'
services:
#mssql docker
  meetgo-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - meetgonet

  meetgo-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=meetgo-sql,1433;Database=meetgo;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5001:5001
    networks:
      - meetgonet      
    links:
      - meetgo-sql
    depends_on:
      - meetgo-sql
      
networks:
  meetgonet:
    driver: bridge 